# -*- coding: utf-8 -*-
"""Depth_Data_Cleaning.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1oGIRBpTBzEOyG2qzH3-T8YPRv5cYoTVU
"""

#from google.colab import drive
#drive.mount('/content/drive')

import pandas as pd
df=pd.read_csv("all_month.csv", parse_dates=["time"], index_col=['time'])

df.sort_index(inplace=True)

df.head()

df.tail()

df.columns

df.info()

# seperating 'place' column and only consider city by seperating the location by ', '
newdf = df['place'].str.split(', ', expand=True)

df['location'] = newdf[1]

df1 = df[(df['location'] == 'CA') & (df['type'] == 'earthquake') ]

df1.shape

df1.head()

df1.drop(df.columns.difference(['depth']),axis=1, inplace=True)

df1.shape

ts=df1['depth'].resample("10T").mean()

len(ts)

ts.head()

df_dep=ts.to_frame()

df_dep.head()

df_dep.depth.isna().sum()

df_dep.fillna( method='ffill',inplace=True)

df_dep.shape

df_dep.head()


df_dep.head()